import { StyleSheet } from 'react-native';

export const authModalStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.72)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 18,
    paddingVertical: 24,
    position: 'relative',
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  card: {
    width: '100%',
    maxWidth: 980,
    minHeight: 600,
    backgroundColor: '#ffffff',
    borderRadius: 24,
    overflow: 'hidden',
    flexDirection: 'row',
    shadowColor: '#0f172a',
    shadowOpacity: 0.22,
    shadowRadius: 30,
    shadowOffset: {
      width: 0,
      height: 16,
    },
    elevation: 14,
  },
  cardCompact: {
    width: '100%',
    maxWidth: 980,
    maxHeight: '92%',
    backgroundColor: '#ffffff',
    borderRadius: 24,
    overflow: 'hidden',
    flexDirection: 'column',
    shadowColor: '#0f172a',
    shadowOpacity: 0.22,
    shadowRadius: 30,
    shadowOffset: {
      width: 0,
      height: 16,
    },
    elevation: 14,
  },
  closeButton: {
    position: 'absolute',
    top: 16,
    right: 16,
    zIndex: 5,
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(15, 23, 42, 0.06)',
  },
  closeButtonText: {
    fontSize: 20,
    lineHeight: 20,
    color: '#475569',
    fontWeight: '500',
  },
  leftPanel: {
    flex: 1,
    backgroundColor: '#111827',
    paddingHorizontal: 34,
    paddingVertical: 36,
    justifyContent: 'space-between',
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  brandMark: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#2563eb',
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandMarkText: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '800',
  },
  brandText: {
    fontSize: 22,
    color: '#ffffff',
    fontWeight: '800',
  },
  brandTextAccent: {
    color: '#2f80ff',
    fontWeight: '800',
  },
  leftTitle: {
    marginTop: 28,
    fontSize: 36,
    lineHeight: 44,
    color: '#ffffff',
    fontWeight: '800',
    maxWidth: 320,
  },
  leftTitleAccent: {
    color: '#2f80ff',
  },
  leftSubtitle: {
    marginTop: 18,
    fontSize: 17,
    lineHeight: 26,
    color: '#94a3b8',
    maxWidth: 350,
  },
  benefitList: {
    marginTop: 28,
    gap: 18,
  },
  benefitItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  benefitIcon: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1.5,
    borderColor: '#2f80ff',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  benefitIconText: {
    color: '#2f80ff',
    fontSize: 11,
    fontWeight: '800',
    lineHeight: 11,
  },
  benefitText: {
    flex: 1,
    fontSize: 15,
    lineHeight: 22,
    color: '#cbd5e1',
  },
  leftFooter: {
    marginTop: 28,
    paddingTop: 18,
    borderTopWidth: 1,
    borderTopColor: 'rgba(148, 163, 184, 0.14)',
  },
  leftFooterText: {
    fontSize: 12,
    lineHeight: 18,
    color: '#64748b',
  },
  rightPanel: {
    flex: 1.2,
    backgroundColor: '#ffffff',
    paddingHorizontal: 34,
    paddingTop: 34,
    paddingBottom: 30,
    justifyContent: 'center',
  },
  compactHero: {
    backgroundColor: '#111827',
    paddingHorizontal: 24,
    paddingTop: 32,
    paddingBottom: 28,
  },
  compactHeroTitle: {
    marginTop: 22,
    fontSize: 30,
    lineHeight: 36,
    color: '#ffffff',
    fontWeight: '800',
  },
  compactHeroSubtitle: {
    marginTop: 12,
    fontSize: 15,
    lineHeight: 23,
    color: '#94a3b8',
  },
  tabs: {
    width: '100%',
    maxWidth: 340,
    backgroundColor: '#eef2f7',
    borderRadius: 14,
    padding: 4,
    flexDirection: 'row',
    alignSelf: 'flex-start',
    marginBottom: 30,
  },
  tabButton: {
    flex: 1,
    minHeight: 46,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabButtonActive: {
    backgroundColor: '#ffffff',
    shadowColor: '#0f172a',
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    elevation: 3,
  },
  tabText: {
    fontSize: 16,
    color: '#64748b',
    fontWeight: '700',
  },
  tabTextActive: {
    color: '#2563eb',
  },
  heading: {
    fontSize: 30,
    lineHeight: 38,
    color: '#0f172a',
    fontWeight: '800',
  },
  subtitle: {
    marginTop: 8,
    fontSize: 16,
    lineHeight: 24,
    color: '#64748b',
    marginBottom: 24,
  },
  form: {
    width: '100%',
    maxWidth: 430,
  },
  fieldGroup: {
    marginBottom: 18,
  },
  fieldLabel: {
    fontSize: 16,
    lineHeight: 24,
    color: '#1e293b',
    fontWeight: '700',
    marginBottom: 10,
  },
  rowBetween: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  forgotLink: {
    fontSize: 14,
    color: '#2563eb',
    fontWeight: '700',
  },
  inputShell: {
    minHeight: 56,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#d9e2ef',
    backgroundColor: '#f8fafc',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    gap: 10,
  },
  inputIcon: {
    width: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  inputIconText: {
    fontSize: 15,
    color: '#94a3b8',
    fontWeight: '800',
  },
  input: {
    flex: 1,
    minHeight: 54,
    fontSize: 16,
    color: '#0f172a',
  },
  inputTrailing: {
    paddingLeft: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  trailingText: {
    fontSize: 18,
    color: '#94a3b8',
  },
  rememberRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 8,
    marginBottom: 20,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 1.5,
    borderColor: '#475569',
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxFilled: {
    backgroundColor: '#111827',
    borderColor: '#111827',
  },
  checkboxMark: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '900',
    lineHeight: 12,
  },
  rememberText: {
    fontSize: 14,
    color: '#334155',
    fontWeight: '600',
  },
  submitButton: {
    minHeight: 50,
    borderRadius: 12,
    backgroundColor: '#1d4ed8',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 18,
  },
  submitButtonDisabled: {
    backgroundColor: '#94a3b8',
  },
  submitButtonText: {
    fontSize: 16,
    color: '#ffffff',
    fontWeight: '800',
  },
  submitButtonArrow: {
    fontSize: 18,
    color: '#ffffff',
    fontWeight: '800',
  },
  formErrorText: {
    marginBottom: 12,
    fontSize: 14,
    lineHeight: 20,
    color: '#dc2626',
    fontWeight: '600',
  },
  footerLinkRow: {
    marginTop: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flexWrap: 'wrap',
    gap: 6,
  },
  footerHint: {
    fontSize: 14,
    color: '#64748b',
  },
  footerLink: {
    fontSize: 15,
    color: '#2563eb',
    fontWeight: '800',
  },
});
